import React from 'react';

/**
 * ConservationTips Component
 * Dynamically displays the conservation recommendations generated by the backend.
 */
function ConservationTips({ tips }) {
  const hasTips = Array.isArray(tips) && tips.length > 0;

  return (
    <div className="card tips-card">
      <div className="card-header">
        <div className="card-title-wrap">
          <span className="card-icon" aria-hidden="true">🌱</span>
          <h2 className="card-title">Tailored Conservation Recommendations</h2>
        </div>
        <span className="tips-count-badge">
          {hasTips ? `${tips.length} Actionable Tips` : 'Smart Recommendations'}
        </span>
      </div>

      <p className="card-intro">
        Actionable suggestions calculated from your consumption pattern to help reduce utility bills and conserve community water reserves:
      </p>

      {hasTips ? (
        <div className="tips-list">
          {tips.map((tip, index) => (
            <div key={index} className="tip-item">
              <div className="tip-number-bubble">{index + 1}</div>
              <div className="tip-content">
                <p className="tip-text">{tip}</p>
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div className="tips-empty">
          <p>No specific tips generated for this pattern. Continue practicing mindful water usage!</p>
        </div>
      )}

      <div className="eco-impact-banner">
        <span className="eco-icon" aria-hidden="true">💡</span>
        <div className="eco-text">
          <strong>Conservation Impact:</strong> Addressing a single leaking toilet flapper can save up to 750 liters per week, reducing household utility expenses significantly.
        </div>
      </div>
    </div>
  );
}

export default ConservationTips;
